ALTER SESSION SET CONTAINER = FREEPDB1;
create table DWH_ROUTINE.PATIENT
(
    ID                             NUMBER(10),
    LETZTE_INFORMATION             DATE,
    STERBEDATUM                    DATE,
    STERBEDATUM_ACC                VARCHAR2(10 char),
    VERSICHERUNGSNUMMER            VARCHAR2(50 char),
    VERSICHERUNGSNUMMER_GUELTIG_AB DATE,
    GEBURTSORT                     VARCHAR2(50 char),
    GEBURTSLAND                    VARCHAR2(3 char),
    PATIENTEN_ID                   VARCHAR2(20 char),
    PID_GESPERRT                   NUMBER(5) not null,
    FAMILIENANGEHOERIGENNUMMER     VARCHAR2(12 char),
    KRANKENKASSENNUMMER            VARCHAR2(12 char),
    KOSTENTRAEGERTYP               VARCHAR2(32 char),
    QUELLEVITALSTATUS              VARCHAR2(64 char),
    IMPORT_JOB                     NUMBER(10),
    ANGELEGT_AM                    DATE,
    SID                            NUMBER(10),
    REVISION                       NUMBER(10),
    PERSONENSTAMM                  NUMBER(10),
    MPI_ID                         NUMBER(10),
    GESCHLECHT                     VARCHAR2(1 char),
    GEBURTSDATUM                   DATE,
    GEBURTSDATUM_ACC               VARCHAR2(10 char),
    TITEL                          VARCHAR2(20 char),
    NAMENZUSATZ                    VARCHAR2(30 char),
    VORNAME                        VARCHAR2(100 char),
    NACHNAME                       VARCHAR2(100 char),
    GEBURTSNAME                    VARCHAR2(50 char),
    FRUEHERE_NAMEN                 VARCHAR2(50 char),
    PHONETIK_VORNAME               VARCHAR2(255 char),
    PHONETIK_NACHNAME              VARCHAR2(255 char),
    TELEFON                        VARCHAR2(50 char),
    TELEFON2                       VARCHAR2(50 char),
    EMAIL                          VARCHAR2(100 char),
    STAATSANGEHOERIGKEIT           VARCHAR2(3 char),
    FAMILIENSTAND                  VARCHAR2(1 char),
    STAAT_ID                       VARCHAR2(3 char),
    BUNDESLAND                     VARCHAR2(2 char),
    ORT                            VARCHAR2(50 char),
    POSTLEITZAHL                   VARCHAR2(10 char),
    STRASSE                        VARCHAR2(60 char),
    HAUSNUMMER                     VARCHAR2(50 char),
    ADRESSZUSATZ                   VARCHAR2(255 char),
    POSTFIX                        VARCHAR2(1 char),
    GKZ                            VARCHAR2(8 char),
    NACHSORGEPASSNR                VARCHAR2(50 char),
    AHVNUMMER                      VARCHAR2(20 char),
    REFERENZNUMMER_VORGABE         VARCHAR2(50 char),
    PATIENTEN_IDS_VORHER           VARCHAR2(500 char),
    AKTION_ID                      NUMBER(10),
    PSEUDONYM                      VARCHAR2(36 char),
    SECRETKEY                      VARCHAR2(50 char),
    ZU_LOESCHEN                    NUMBER(5) not null,
    ZUGRIFF_GESPERRT               NUMBER(5) not null,
    NAMENSVORSATZ                  VARCHAR2(50 char),
    ORGANISATIONUNIT_ID            NUMBER(10),
    PATIENTEN_ID2                  VARCHAR2(20 char),
    CRYPTO_KEY                     VARCHAR2(2048 char),
    CRYPTO_IV                      VARCHAR2(255 char),
    CRYPTO_KEY_ID                  VARCHAR2(50 char),
    DUBLETTENPRUEFUNG              DATE,
    BEARBEITET_AM                  DATE,
    BEIHILFESTELLE                 VARCHAR2(255 char),
    CRYPTO_TIMESTAMP               DATE
)
    /

INSERT INTO DWH_ROUTINE.PATIENT (ID, LETZTE_INFORMATION, STERBEDATUM, STERBEDATUM_ACC, VERSICHERUNGSNUMMER,
                                 VERSICHERUNGSNUMMER_GUELTIG_AB, GEBURTSORT, GEBURTSLAND, PATIENTEN_ID, PID_GESPERRT,
                                 FAMILIENANGEHOERIGENNUMMER, KRANKENKASSENNUMMER, KOSTENTRAEGERTYP, QUELLEVITALSTATUS,
                                 IMPORT_JOB, ANGELEGT_AM, SID, REVISION, PERSONENSTAMM, MPI_ID, GESCHLECHT,
                                 GEBURTSDATUM, GEBURTSDATUM_ACC, TITEL, NAMENZUSATZ, VORNAME, NACHNAME, GEBURTSNAME,
                                 FRUEHERE_NAMEN, PHONETIK_VORNAME, PHONETIK_NACHNAME, TELEFON, TELEFON2, EMAIL,
                                 STAATSANGEHOERIGKEIT, FAMILIENSTAND, STAAT_ID, BUNDESLAND, ORT, POSTLEITZAHL, STRASSE,
                                 HAUSNUMMER, ADRESSZUSATZ, POSTFIX, GKZ, NACHSORGEPASSNR, AHVNUMMER,
                                 REFERENZNUMMER_VORGABE, PATIENTEN_IDS_VORHER, AKTION_ID, PSEUDONYM, SECRETKEY,
                                 ZU_LOESCHEN, ZUGRIFF_GESPERRT, NAMENSVORSATZ, ORGANISATIONUNIT_ID, PATIENTEN_ID2,
                                 CRYPTO_KEY, CRYPTO_IV, CRYPTO_KEY_ID, DUBLETTENPRUEFUNG, BEARBEITET_AM, BEIHILFESTELLE,
                                 CRYPTO_TIMESTAMP)
values (1, DATE '2025-01-01', DATE '2021-01-01', 'exact', 'X123456781', DATE '2001-01-01', null, null, '1055555999', 0,
        null, '123456789', null, null, null, TIMESTAMP '2021-01-01 11:11:11', 1111, 1, 1, 1, 'm', DATE '1999-09-09',
        null, null, null, 'Testvorname1', 'Testnachname1', null, null, null, null, null, null, null, 'DE',
        null, 'DE', null, 'Testort', '99999', 'Teststr. 123', null, null, null, null, null, null, null,
        '1002222221', null, null, null, 0, 0, null, null, null, null, null, null, null,
        TIMESTAMP '2026-01-01 01:01:01', null, null);
INSERT INTO DWH_ROUTINE.PATIENT (ID, LETZTE_INFORMATION, STERBEDATUM, STERBEDATUM_ACC, VERSICHERUNGSNUMMER,
                                 VERSICHERUNGSNUMMER_GUELTIG_AB, GEBURTSORT, GEBURTSLAND, PATIENTEN_ID, PID_GESPERRT,
                                 FAMILIENANGEHOERIGENNUMMER, KRANKENKASSENNUMMER, KOSTENTRAEGERTYP, QUELLEVITALSTATUS,
                                 IMPORT_JOB, ANGELEGT_AM, SID, REVISION, PERSONENSTAMM, MPI_ID, GESCHLECHT,
                                 GEBURTSDATUM, GEBURTSDATUM_ACC, TITEL, NAMENZUSATZ, VORNAME, NACHNAME, GEBURTSNAME,
                                 FRUEHERE_NAMEN, PHONETIK_VORNAME, PHONETIK_NACHNAME, TELEFON, TELEFON2, EMAIL,
                                 STAATSANGEHOERIGKEIT, FAMILIENSTAND, STAAT_ID, BUNDESLAND, ORT, POSTLEITZAHL, STRASSE,
                                 HAUSNUMMER, ADRESSZUSATZ, POSTFIX, GKZ, NACHSORGEPASSNR, AHVNUMMER,
                                 REFERENZNUMMER_VORGABE, PATIENTEN_IDS_VORHER, AKTION_ID, PSEUDONYM, SECRETKEY,
                                 ZU_LOESCHEN, ZUGRIFF_GESPERRT, NAMENSVORSATZ, ORGANISATIONUNIT_ID, PATIENTEN_ID2,
                                 CRYPTO_KEY, CRYPTO_IV, CRYPTO_KEY_ID, DUBLETTENPRUEFUNG, BEARBEITET_AM, BEIHILFESTELLE,
                                 CRYPTO_TIMESTAMP)
values (2, DATE '2025-01-01', DATE '2022-02-02', 'exact', 'X123456782', DATE '2001-01-01', null, null, '1055555929', 0,
        null, '123456789', null, null, null, TIMESTAMP '2021-01-01 11:11:11', 1111, 1, 1, 1, 'm', DATE '1999-09-19',
        null, null, null, 'Testvorname2', 'Testnachname2', null, null, null, null, null, null, null, 'DE',
        null, 'DE', null, 'Testort', '99999', 'Teststr. 123', null, null, null, null, null, null, null,
        '1002222222', null, null, null, 0, 0, null, null, null, null, null, null, null,
        TIMESTAMP '2026-01-01 01:01:02', null, null);
INSERT INTO DWH_ROUTINE.PATIENT (ID, LETZTE_INFORMATION, STERBEDATUM, STERBEDATUM_ACC, VERSICHERUNGSNUMMER,
                                 VERSICHERUNGSNUMMER_GUELTIG_AB, GEBURTSORT, GEBURTSLAND, PATIENTEN_ID, PID_GESPERRT,
                                 FAMILIENANGEHOERIGENNUMMER, KRANKENKASSENNUMMER, KOSTENTRAEGERTYP, QUELLEVITALSTATUS,
                                 IMPORT_JOB, ANGELEGT_AM, SID, REVISION, PERSONENSTAMM, MPI_ID, GESCHLECHT,
                                 GEBURTSDATUM, GEBURTSDATUM_ACC, TITEL, NAMENZUSATZ, VORNAME, NACHNAME, GEBURTSNAME,
                                 FRUEHERE_NAMEN, PHONETIK_VORNAME, PHONETIK_NACHNAME, TELEFON, TELEFON2, EMAIL,
                                 STAATSANGEHOERIGKEIT, FAMILIENSTAND, STAAT_ID, BUNDESLAND, ORT, POSTLEITZAHL, STRASSE,
                                 HAUSNUMMER, ADRESSZUSATZ, POSTFIX, GKZ, NACHSORGEPASSNR, AHVNUMMER,
                                 REFERENZNUMMER_VORGABE, PATIENTEN_IDS_VORHER, AKTION_ID, PSEUDONYM, SECRETKEY,
                                 ZU_LOESCHEN, ZUGRIFF_GESPERRT, NAMENSVORSATZ, ORGANISATIONUNIT_ID, PATIENTEN_ID2,
                                 CRYPTO_KEY, CRYPTO_IV, CRYPTO_KEY_ID, DUBLETTENPRUEFUNG, BEARBEITET_AM, BEIHILFESTELLE,
                                 CRYPTO_TIMESTAMP)
values (3, DATE '2025-01-01', null, null, 'X123456783', DATE '2001-01-01', null, null, '1055555939', 0,
        null, '123456789', null, null, null, TIMESTAMP '2021-01-01 11:11:11', 1111, 1, 1, 1, 'm', DATE '1999-09-29',
        null, null, null, 'Testvorname3', 'Testnachname3', null, null, null, null, null, null, null, 'DE',
        null, 'DE', null, 'Testort', '99999', 'Teststr. 123', null, null, null, null, null, null, null,
        '1002222223', null, null, null, 0, 0, null, null, null, null, null, null, null,
        TIMESTAMP '2026-01-01 01:01:03', null, null);
