ALTER SESSION SET CONTAINER = FREEPDB1;
create table DWH_ROUTINE.PROZEDUR
(
    id                            NUMBER,
    patient_id                    NUMBER,
    beginndatum                   DATE,
    beginnuhrzeit                 DATE,
    beginnzeitpunkt_acc           VARCHAR2(10 char),
    enddatum                      DATE,
    enduhrzeit                    DATE,
    text                          VARCHAR2(255 char),
    hauptprozedur_id              NUMBER,
    prozedurtyp                   NUMBER,
    data_form_id                  NUMBER,
    geloescht                     NUMBER(1),
    status                        NUMBER,
    dokumentierende_fachabteilung NUMBER,
    mpi_id                        NUMBER,
    html_schnipsel_komprimiert    VARCHAR2(50 char),
    html_schnipsel_detailiert     VARCHAR2(50 char),
    data_form_entry_id            NUMBER,
    filterkategorien              VARCHAR2(250 char),
    html_schnipsel_kalender       VARCHAR2(50 char),
    import_job                    NUMBER,
    status_zertifizierung         NUMBER,
    status_dkg                    NUMBER,
    status_eusoma                 NUMBER,
    hat_dokumente                 NUMBER(1),
    sid                           NUMBER,
    guid                          NUMBER,
    revision                      NUMBER,
    bearbeitung_status            NUMBER,
    aktuelle_seite                NUMBER,
    migriert                      NUMBER(1),
    mig_referenz_name             VARCHAR2(100 char),
    mig_referenz_id               VARCHAR2(100 char),
    mig_referenz_zusatz           VARCHAR2(250 char),
    mig_lkr_meldung               NUMBER(1),
    mig_lkr_meldung_id            VARCHAR2(100 char),
    aktion_id                     NUMBER,
    zuletzt_geaendert             NUMBER,
    bearbeiter                    VARCHAR2(255 char),
    crypto_key                    VARCHAR2(2048 char),
    crypto_iv                     VARCHAR2(255 char),
    crypto_chiffrat               VARCHAR2(50 char),
    crypto_key_id                 VARCHAR2(50 char),
    erstelldatum                  DATE,
    ersteller                     VARCHAR2(255 char),
    cache_timestamp               NUMBER,
    idat_crypto_key               VARCHAR2(2048 char),
    idat_crypto_iv                VARCHAR2(255 char),
    idat_crypto_chiffrat          VARCHAR2(50 char),
    idat_crypto_key_id            VARCHAR2(50 char) ,
    idat_crypto_timestamp         DATE
)
/

INSERT INTO DWH_ROUTINE.PROZEDUR (id, patient_id, beginndatum, beginnuhrzeit, beginnzeitpunkt_acc, enddatum, enduhrzeit,
                                  text, hauptprozedur_id, prozedurtyp, data_form_id, geloescht, status,
                                  dokumentierende_fachabteilung, mpi_id, html_schnipsel_komprimiert,
                                  html_schnipsel_detailiert, data_form_entry_id, filterkategorien, html_schnipsel_kalender,
                                  import_job, status_zertifizierung, status_dkg, status_eusoma, hat_dokumente, sid, guid,
                                  revision, bearbeitung_status, aktuelle_seite, migriert, mig_referenz_name,
                                  mig_referenz_id, mig_referenz_zusatz, mig_lkr_meldung, mig_lkr_meldung_id, aktion_id,
                                  zuletzt_geaendert, bearbeiter, crypto_key, crypto_iv, crypto_chiffrat, crypto_key_id,
                                  erstelldatum, ersteller, cache_timestamp, idat_crypto_key, idat_crypto_iv,
                                  idat_crypto_chiffrat, idat_crypto_key_id, idat_crypto_timestamp)
values (21, 1, null, null, null, null, null, null, null, null,
        null, null, null, null, null, null, null, null, null, null, null, null,
        null, null, null, null, null, null, null, null, null, null, null, null, null,
        null, null, null, null, null, null, null, null,null, null, null, null, null,
        null, null, null);
INSERT INTO DWH_ROUTINE.PROZEDUR (id, patient_id, beginndatum, beginnuhrzeit, beginnzeitpunkt_acc, enddatum, enduhrzeit,
                                  text, hauptprozedur_id, prozedurtyp, data_form_id, geloescht, status,
                                  dokumentierende_fachabteilung, mpi_id, html_schnipsel_komprimiert,
                                  html_schnipsel_detailiert, data_form_entry_id, filterkategorien, html_schnipsel_kalender,
                                  import_job, status_zertifizierung, status_dkg, status_eusoma, hat_dokumente, sid, guid,
                                  revision, bearbeitung_status, aktuelle_seite, migriert, mig_referenz_name,
                                  mig_referenz_id, mig_referenz_zusatz, mig_lkr_meldung, mig_lkr_meldung_id, aktion_id,
                                  zuletzt_geaendert, bearbeiter, crypto_key, crypto_iv, crypto_chiffrat, crypto_key_id,
                                  erstelldatum, ersteller, cache_timestamp, idat_crypto_key, idat_crypto_iv,
                                  idat_crypto_chiffrat, idat_crypto_key_id, idat_crypto_timestamp)
values (22, 2, null, null, null, null, null, null, null, null,
        null, null, null, null, null, null, null, null, null, null, null, null,
        null, null, null, null, null, null, null, null, null, null, null, null, null,
        null, null, null, null, null, null, null, null,null, null, null, null, null,
        null, null, null);
INSERT INTO DWH_ROUTINE.PROZEDUR (id, patient_id, beginndatum, beginnuhrzeit, beginnzeitpunkt_acc, enddatum, enduhrzeit,
                                  text, hauptprozedur_id, prozedurtyp, data_form_id, geloescht, status,
                                  dokumentierende_fachabteilung, mpi_id, html_schnipsel_komprimiert,
                                  html_schnipsel_detailiert, data_form_entry_id, filterkategorien, html_schnipsel_kalender,
                                  import_job, status_zertifizierung, status_dkg, status_eusoma, hat_dokumente, sid, guid,
                                  revision, bearbeitung_status, aktuelle_seite, migriert, mig_referenz_name,
                                  mig_referenz_id, mig_referenz_zusatz, mig_lkr_meldung, mig_lkr_meldung_id, aktion_id,
                                  zuletzt_geaendert, bearbeiter, crypto_key, crypto_iv, crypto_chiffrat, crypto_key_id,
                                  erstelldatum, ersteller, cache_timestamp, idat_crypto_key, idat_crypto_iv,
                                  idat_crypto_chiffrat, idat_crypto_key_id, idat_crypto_timestamp)
values (23, 3, null, null, null, null, null, null, null, null,
        null, null, null, null, null, null, null, null, null, null, null, null,
        null, null, null, null, null, null, null, null, null, null, null, null, null,
        null, null, null, null, null, null, null, null,null, null, null, null, null,
        null, null, null);
