# @ignored
lib-version: 3.2.0

fhir:
  codings:
    loinc:
      system: "${fhir.systems.loinc}"
      version: "2.82"
    snomed:
      system: "${fhir.systems.snomed}"
      version: "http://snomed.info/sct/900000000000207008/version/20250701"
    ops:
      system: "${fhir.systems.ops}"
      version: "2026"
    atc:
      system: "${fhir.systems.atcBfarm}"
      version: "2025"
  extensions:
    condition-asserted-date: "http://hl7.org/fhir/StructureDefinition/condition-assertedDate"
    condition-occurred-following: "http://hl7.org/fhir/StructureDefinition/condition-occurredFollowing"
    ordinal-value: "http://hl7.org/fhir/StructureDefinition/ordinalValue"
    procedure-method: "http://hl7.org/fhir/StructureDefinition/procedure-method"
  systems:
    identifiers:
      base-url: "https://bzkf.github.io/obds-to-fhir/identifiers"
      patient-id: "${fhir.systems.identifiers.base-url}/patient-id"
      vital-status-id: "${fhir.systems.identifiers.base-url}/vital-status-id"
      vital-status-onkostar-patient-table-id: "${fhir.systems.identifiers.base-url}/onkostar-patient-table-vital-status-id"
      primaerdiagnose-condition-id: "${fhir.systems.identifiers.base-url}/primaerdiagnose-condition-id"
      histologie-specimen-id: "${fhir.systems.identifiers.base-url}/histologie-specimen-id"
      studienteilnahme-observation-id: "${fhir.systems.identifiers.base-url}/studienteilnahme-observation-id"
      lymphknotenuntersuchung-observation-id: "${fhir.systems.identifiers.base-url}/lymphknotenuntersuchung-observation-id"
      verlaufshistologie-observation-id: "${fhir.systems.identifiers.base-url}/verlaufshistologie-observation-id"
      verlauf-observation-id: "${fhir.systems.identifiers.base-url}/verlauf-observation-id"
      strahlentherapie-procedure-id: "${fhir.systems.identifiers.base-url}/strahlentherapie-procedure-id"
      strahlentherapie-bestrahlung-procedure-id: "${fhir.systems.identifiers.base-url}/strahlentherapie-bestrahlung-procedure-id"
      systemische-therapie-procedure-id: "${fhir.systems.identifiers.base-url}/systemische-therapie-procedure-id"
      systemische-therapie-medication-statement-id: "${fhir.systems.identifiers.base-url}/systemische-therapie-medication-statement-id"
      systemische-therapie-medication-id: "${fhir.systems.identifiers.base-url}/systemische-therapie-medication-id"
      allgemeiner-leistungszustand-ecog-observation-id: "${fhir.systems.identifiers.base-url}/allgemeiner-leistungszustand-ecog-id"
      fernmetastasen-observation-id: "${fhir.systems.identifiers.base-url}/fernmetastasen-observation-id"
      residualstatus-observation-id: "${fhir.systems.identifiers.base-url}/residualstatus-observation-id"
      histologiebefund-diagnostic-report-id: "${fhir.systems.identifiers.base-url}/histologiebefund-diagnostic-report-id"
      genetische-variante-observation-id: "${fhir.systems.identifiers.base-url}/genetische-variante-observation-id"
      nebenwirkung-adverse-event-id: "${fhir.systems.identifiers.base-url}/nebenwirkung-adverse-event-id"
      tod-observation-id: "${fhir.systems.identifiers.base-url}/tod-observation-id"
      tod-observation-onkostar-patient-table-id: "${fhir.systems.identifiers.base-url}/onkostar-patient-table-tod-observation-id"
      grading-observation-id: "${fhir.systems.identifiers.base-url}/grading-observation-id"
      tnm-grouping-observation-id: "${fhir.systems.identifiers.base-url}/tnm-grouping-observation-id"
      tnm-t-kategorie-observation-id: "${fhir.systems.identifiers.base-url}/tnm-t-kategorie-observation-id"
      tnm-n-kategorie-observation-id: "${fhir.systems.identifiers.base-url}/tnm-n-kategorie-observation-id"
      tnm-m-kategorie-observation-id: "${fhir.systems.identifiers.base-url}/tnm-m-kategorie-observation-id"
      tnm-l-kategorie-observation-id: "${fhir.systems.identifiers.base-url}/tnm-l-kategorie-observation-id"
      tnm-pn-kategorie-observation-id: "${fhir.systems.identifiers.base-url}/tnm-pn-kategorie-observation-id"
      tnm-s-kategorie-observation-id: "${fhir.systems.identifiers.base-url}/tnm-s-kategorie-observation-id"
      tnm-v-kategorie-observation-id: "${fhir.systems.identifiers.base-url}/tnm-v-kategorie-observation-id"
      tnm-a-symbol-observation-id: "${fhir.systems.identifiers.base-url}/tnm-a-symbol-observation-id"
      tnm-m-symbol-observation-id: "${fhir.systems.identifiers.base-url}/tnm-m-symbol-observation-id"
      tnm-r-symbol-observation-id: "${fhir.systems.identifiers.base-url}/tnm-r-symbol-observation-id"
      tnm-y-symbol-observation-id: "${fhir.systems.identifiers.base-url}/tnm-y-symbol-observation-id"
      tumorkonferenz-care-plan-id: "${fhir.systems.identifiers.base-url}/tumorkonferenz-care-plan-id"
      weitere-klassifikation-observation-id: "${fhir.systems.identifiers.base-url}/weitere-klassifikation-observation-id"
      erstdiagnose-evidenz-list-id: "${fhir.systems.identifiers.base-url}/erstdiagnose-evidenz-list-id"
      fruehere-tumorerkrankung-condition-id: "${fhir.systems.identifiers.base-url}/fruehere-tumorerkrankung-condition-id"
      prostata-psa-observation-id: "${fhir.systems.identifiers.base-url}/prostata-psa-observation-id"
      prostata-anzahl-stanzen-observation-id: "${fhir.systems.identifiers.base-url}/prostata-anzahl-stanzen-observation-id"
      prostata-anzahl-positive-stanzen-observation-id: "${fhir.systems.identifiers.base-url}/prostata-anzahl-positive-stanzen-observation-id"
      prostata-ca-befall-stanze-observation-id: "${fhir.systems.identifiers.base-url}/prostata-ca-befall-stanze-observation-id"
      prostata-clavien-dindo-observation-id: "${fhir.systems.identifiers.base-url}/prostata-clavien-dindo-observation-id"
      prostata-gleason-patterns-observation-id: "${fhir.systems.identifiers.base-url}/prostata-gleason-patterns-observation-id"
      prostata-gleason-score-observation-id: "${fhir.systems.identifiers.base-url}/prostata-gleason-score-observation-id"
      obds-meldung-id: "${fhir.systems.identifiers.base-url}/obds-meldung-id"
      provenance-id: "${fhir.systems.identifiers.base-url}/provenance-id"
      obds-to-fhir-device-id: "${fhir.systems.identifiers.base-url}/obds-to-fhir-device-id"
      operation-procedure-id: "${fhir.systems.identifiers.base-url}/operation-procedure-id"


    # external systems
    v3-data-operation: "http://terminology.hl7.org/CodeSystem/v3-DataOperation"
    provenance-participant-type: "http://terminology.hl7.org/CodeSystem/provenance-participant-type"
    v3-participation-type: "http://terminology.hl7.org/CodeSystem/v3-ParticipationType"
    v3-observation-value: "http://terminology.hl7.org/CodeSystem/v3-ObservationValue"
    identifier-type: "http://terminology.hl7.org/CodeSystem/v2-0203"
    diagnostic-service-section: "http://terminology.hl7.org/CodeSystem/v2-0074"
    loinc: "http://loinc.org"
    icdo3Morphologie: "http://terminology.hl7.org/CodeSystem/icd-o-3"

    icd10gm: "http://fhir.de/CodeSystem/bfarm/icd-10-gm"
    snomed: "http://snomed.info/sct"
    ops: "http://fhir.de/CodeSystem/bfarm/ops"
    ucum: "http://unitsofmeasure.org"
    condition-ver-status: "http://terminology.hl7.org/CodeSystem/condition-ver-status"
    atcBfarm: "http://fhir.de/CodeSystem/bfarm/atc"
    observation-category: "http://terminology.hl7.org/CodeSystem/observation-category"
    meddra: "https://www.meddra.org"

  mappings:
    meta:
      # -- Value to set for the meta.source field in all generated resources
      source: ""
    ## -- regex to apply to the `Patient_ID` before setting it to `Patient.identifier.value`. Must contain one capture group.
    # Use, e.g. `^0*([1-9]\d*)$` to match any numeric value, ignoring any prefixed 0s.
    patient-id-regex: "^(.*)$"
    create-patient-resources:
      # -- Whether Patient resources should be created. Useful to disable if you already create FHIR resources
      # from a different source.
      enabled: true
      # -- If enabled, sets Patient.id to the mapped Patient_ID value instead of a hash of the identifier.
      use-obds-patient-id-as-resource-id: false
    create-provenance-resources:
      # -- Whether Provenance resources should be created. They include the oBDS Meldung_ID as the entity.what
      # of the FHIR Resource derived from the Meldung. Multiple resources are mapped from a single Meldung_ID.
      enabled: false
    substanz-to-atc:
      # -- path to a CSV file containing additional Substanz -> ATC code mappings.
      # The CSV file needs to have two headings: `Substanzbezeichnung;ATC-Code`, all columns must be seperated by `;`.
      # The job always ships with the mappings from <https://plattform65c.atlassian.net/wiki/spaces/UMK/pages/15532506/Substanzen>,
      # if the extra file contains duplicate mappings to the default ones, the ones from this file take precedence.
      extra-mappings-file-path: ""
    weitere-klassifikationen:
      # -- ⚠️ Experimental! Path to a CSV file containing additional Weitere Klassifikationen -> SNOMED code mappings.
      # The CSV file needs to have these columns: `name;stadium;snomed_code;snomed_display;value_snomed_code;value_snomed_display`, all columns must be seperated by `;`.
      # if the extra file contains duplicate mappings to the default ones, the ones from this file take precedence.
      extra-mappings-file-path: ""
