ALTER SESSION SET CONTAINER = FREEPDB1;
create table DWH_ROUTINE.STG_ONKOSTAR_LKR_EXPORT
(
    ID               NUMBER(10),
    ERSTELLT_AM      TIMESTAMP(6) not null,
    EXPORTIERT_AM    TIMESTAMP(6),
    STATUS           NUMBER(10)   not null,
    ABSENDER_OE      NUMBER(10)   not null,
    GEMELDET_AN      NUMBER(10),
    FORMAT           NUMBER(10)   not null,
    EXPORT_JOB       NUMBER(10),
    PERSONENSTAMM_ID NUMBER(10),
    STORNIERT_AM     TIMESTAMP(6)
)
    /


INSERT INTO DWH_ROUTINE.STG_ONKOSTAR_LKR_EXPORT (ID, ERSTELLT_AM, EXPORTIERT_AM, STATUS, ABSENDER_OE, GEMELDET_AN,
                                                 FORMAT, EXPORT_JOB, PERSONENSTAMM_ID, STORNIERT_AM)
VALUES (1, TO_TIMESTAMP('2021-04-27 12:07:28.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null, 1, 1, 9, 8, 29, 2, null);

INSERT INTO DWH_ROUTINE.STG_ONKOSTAR_LKR_EXPORT (ID, ERSTELLT_AM, EXPORTIERT_AM, STATUS, ABSENDER_OE, GEMELDET_AN,
                                                 FORMAT, EXPORT_JOB, PERSONENSTAMM_ID, STORNIERT_AM)
VALUES (2, TO_TIMESTAMP('2021-04-27 12:11:57.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null, 1, 1, 9, 8, 30, 2, null);

INSERT INTO DWH_ROUTINE.STG_ONKOSTAR_LKR_EXPORT (ID, ERSTELLT_AM, EXPORTIERT_AM, STATUS, ABSENDER_OE, GEMELDET_AN,
                                                 FORMAT, EXPORT_JOB, PERSONENSTAMM_ID, STORNIERT_AM)
VALUES (3, TO_TIMESTAMP('2021-05-05 12:05:31.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null, 1, 1, 9, 8, 32, 2, null);
