name: validate-fhir-resources

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions: read-all

jobs:
  validate-fhir-resource:
    name: Validate FHIR resources
    runs-on: ubuntu-22.04
    container: ghcr.io/miracum/ig-build-tools:v2.1.19@sha256:b77f3dc82a185f87cd853fade50f6e4afd0bce64b9a0d2a302004078f0025eec
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Restore FHIR package dependencies
        run: |
          fhir restore

      - name: Validate generated FHIR resources
        # TODO: switch to 'xargs' or for loop so if any validation fails, the entire command fails.
        #       currently not done since we get false errors like:
        #       'error: Code 'C72.0' from system 'http://fhir.de/CodeSystem/bfarm/icd-10-gm' does not exist in the value set 'ICD10GM' (http://fhir.de/ValueSet/bfarm/icd-10-gm)'
        run: |
          find src/test/java/snapshots -name "*.fhir.json" -exec echo "Validating: {}" \; -exec fhir validate --verbose --fail "{}" \;
